apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: phanminhtuan/tuan-app-repo:ee2b5fd572f97f592a1e4a2006c5713516e43ec8
          ports:
            - containerPort: 80
