apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: ghcr.io/tuanpm2003/tuan-app-repo:ed3f7c9d25a966cc694aac9a6280301a981df894
          ports:
            - containerPort: 80
