apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: ghcr.io/tuanpm2003/tuan-app-repo:4734418c29a954d649ba36a0dff5c7aecdfb4578
          ports:
            - containerPort: 80
